<?php

declare(strict_types=1);

namespace SQLCraft\Tests\Unit\Platform;

use InvalidArgumentException;
use PHPUnit\Framework\TestCase;
use SQLCraft\Capabilities\Capability;
use SQLCraft\Capabilities\CapabilityNotSupportedException;
use SQLCraft\Contracts\Connection\ConnectionInterface;
use SQLCraft\Contracts\Connection\ResultInterface;
use SQLCraft\DTO\ColumnMeta;
use SQLCraft\DTO\IndexColumnMeta;
use SQLCraft\DTO\IndexMeta;
use SQLCraft\Platform\PostgreSQLPlatform;
use SQLCraft\ValueObjects\DataType;
use SQLCraft\ValueObjects\DefaultValue;
use SQLCraft\ValueObjects\Identifier;
use SQLCraft\ValueObjects\IndexType;
use SQLCraft\ValueObjects\QualifiedName;
use SQLCraft\ValueObjects\ServerVersion;

final class PostgreSQLPlatformTest extends TestCase
{
    public function test_it_describes_postgre_sql_defaults_and_capabilities(): void
    {
        $platform = new PostgreSQLPlatform();

        self::assertSame('pgsql', $platform->getName());
        self::assertNull($platform->getFlavor());
        self::assertSame('UTF8', $platform->getDefaultCharset());
        self::assertTrue($platform->supportsSchemas());
        self::assertTrue($platform->getCapabilitySet(new ServerVersion('16.0'))->has(Capability::GeneratedColumns));
        self::assertFalse($platform->getCapabilitySet(new ServerVersion('10.0'))->has(Capability::Procedure));
        self::assertTrue($platform->getCapabilitySet(new ServerVersion('11.0'))->has(Capability::Procedure));
        self::assertTrue($platform->getCapabilitySet(new ServerVersion('10.0'))->has(Capability::PartialIndexes));
    }

    public function test_it_detects_server_version_from_the_connection(): void
    {
        $result = self::createMock(ResultInterface::class);
        $result->method('fetchColumn')->willReturn(['16.4']);
        $connection = self::createMock(ConnectionInterface::class);
        $connection->expects(self::once())->method('query')->with('SHOW server_version')->willReturn($result);

        self::assertSame('16.4', (string) (new PostgreSQLPlatform())->getServerVersion($connection));
    }

    public function test_it_quotes_values_and_paginates(): void
    {
        $platform = new PostgreSQLPlatform();

        self::assertSame('"a""b"', $platform->quoteIdentifier(new Identifier('a"b')));
        self::assertSame('TRUE', $platform->quoteValue(true));
        self::assertSame("'a''b'", $platform->quoteValue("a'b"));
        self::assertSame("decode('00ff', 'hex')", $platform->quoteBinary("\x00\xff"));
        self::assertSame('SELECT * LIMIT 10 OFFSET 20', $platform->applyPagination('SELECT *', 10, 20));

        $this->expectException(InvalidArgumentException::class);
        $platform->applyPagination('SELECT *', 10, -1);
    }

    public function test_it_renders_schema_aware_ddl(): void
    {
        $platform = new PostgreSQLPlatform();
        $table = new QualifiedName(new Identifier('users'), new Identifier('public'));
        $column = new ColumnMeta(
            name: 'id',
            dataType: new DataType('BIGINT'),
            nullable: false,
            autoIncrement: true,
            primary: false,
            generated: false,
            default: DefaultValue::nullValue(),
            collation: null,
            comment: null,
            onUpdate: null,
            privileges: [],
            origName: null,
            defaultConstraintName: null,
        );
        $index = new IndexMeta(
            name: 'users_pk',
            type: IndexType::PRIMARY,
            columns: [new IndexColumnMeta('id', false, null, null)],
            unique: true,
            comment: null,
            algorithm: null,
            filterExpression: 'id > 0',
        );

        self::assertSame(
            'CREATE TABLE "public"."users" ("id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY) WITH (fillfactor=80)',
            $platform->renderCreateTableStatement(
                $table,
                [$platform->renderColumnDefinition($column)],
                [],
                ['with' => 'fillfactor=80'],
            ),
        );
        self::assertSame(
            'CREATE UNIQUE INDEX "users_pk" ON "public"."users" ("id" ASC) WHERE id > 0',
            $platform->renderCreateIndexStatement($table, $index),
        );
    }

    public function test_it_returns_introspection_sql_and_rejects_variables(): void
    {
        $platform = new PostgreSQLPlatform();
        $table = new QualifiedName(new Identifier('users'), new Identifier('public'));

        self::assertStringContainsString('pg_database', $platform->getDatabasesSql());
        self::assertStringContainsString("table_schema = 'public'", $platform->getColumnsSql($table));
        self::assertStringContainsString('pg_stat_activity', $platform->getProcesslistSql());
        self::assertStringContainsString('information_schema.sequences', $platform->getSequencesSql());

        try {
            $platform->getVariablesSql();
            self::fail('Expected variables capability exception.');
        } catch (CapabilityNotSupportedException $exception) {
            self::assertSame(Capability::Variables, $exception->capability);
            self::assertSame('pgsql', $exception->platform);
        }
    }
}
